### ISSUE TITLE
反射失效

### ISSUE THREAD

**Issue by tao-glow** [zguop/banner#30]
位置：
```
final class PageTransformerAdapter extends OnPageChangeCallback {
    private final LinearLayoutManager mLayoutManager;
```
报错：
```
12-30 17:14:23.466 16738-16738/com.glow.android.beta W/System.err: java.lang.NoSuchFieldException: No field mLayoutManager in class Landroidx/viewpager2/widget/PageTransformerAdapter; (declaration of 'androidx.viewpager2.widget.PageTransformerAdapter' appears in /data/app/com.glow.android.beta-2/base.apk)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at java.lang.Class.getDeclaredField(Native Method)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at com.glow.android.ui.widget.banner.Banner.q(SourceFile:254)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at com.glow.android.ui.widget.banner.Banner.r(SourceFile:69)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at com.glow.android.ui.widget.banner.Banner.<init>(SourceFile:59)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at com.glow.android.ui.widget.banner.Banner.<init>(SourceFile:53)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at java.lang.reflect.Constructor.newInstance(Native Method)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:631)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at androidx.appcompat.app.AppCompatDelegateImpl.w(SourceFile:469)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at androidx.appcompat.app.AppCompatActivity.setContentView(SourceFile:140)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at com.glow.android.ui.pregnant.SwitchToPregnancyActivity.onCreate(SourceFile:55)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.app.Activity.performCreate(Activity.java:6876)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.app.ActivityThread.access$1100(ActivityThread.java:222)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.os.Looper.loop(Looper.java:158)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7229)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
12-30 17:14:23.476 16738-16738/com.glow.android.beta W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by zguop** [comment]
androidx.viewpager2:viewpager2:1.0.0 依赖下

**Comment by tao-glow** [comment]
找到原因了，混淆导致的
