### ISSUE TITLE
魅族 m2 e Android 6.0.1 崩溃

### ISSUE THREAD

**Issue by mapsh** [zguop/banner#6]
03-11 12:12:07.419 31229-31229 E/CrashReport: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean androidx.recyclerview.widget.RecyclerView.canScrollVertically(int)' on a null object reference
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.onInitializeAccessibilityNodeInfo(RecyclerView.java:10378)
        at androidx.viewpager2.widget.ViewPager2$LinearLayoutManagerImpl.onInitializeAccessibilityNodeInfo(ViewPager2.java:1017)
        at com.to.aboomy.pager2.Banner$ProxyLayoutManger.onInitializeAccessibilityNodeInfo(Banner.java:318)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.onInitializeAccessibilityNodeInfo(RecyclerView.java:10348)
        at androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:74)
        at androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:86)
        at android.view.View.onInitializeAccessibilityNodeInfo(View.java:6217)
        at android.view.View.createAccessibilityNodeInfoInternal(View.java:6178)
        at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:22870)
        at android.view.View.createAccessibilityNodeInfo(View.java:6161)
        at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:145)
        at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
        at android.view.View.onInitializeAccessibilityEventInternal(View.java:6115)
        at android.view.View$AccessibilityDelegate.onInitializeAccessibilityEvent(View.java:22782)
        at androidx.core.view.AccessibilityDelegateCompat.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:256)
        at androidx.recyclerview.widget.RecyclerViewAccessibilityDelegate.onInitializeAccessibilityEvent(RecyclerViewAccessibilityDelegate.java:80)
        at androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:76)
        at android.view.View.onInitializeAccessibilityEvent(View.java:6101)
        at androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl.onInitializeAccessibilityEvent(ViewPager2.java:982)
        at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:5968)
        at android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked(View.java:22721)
        at androidx.core.view.AccessibilityDelegateCompat.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:195)
        at androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:112)
        at android.view.View.sendAccessibilityEventUnchecked(View.java:5951)
        at androidx.recyclerview.widget.RecyclerView.sendAccessibilityEventUnchecked(RecyclerView.java:3736)
        at android.view.View.sendAccessibilityEventInternal(View.java:5930)
        at android.view.View$AccessibilityDelegate.sendAccessibilityEvent(View.java:22679)
        at androidx.core.view.AccessibilityDelegateCompat.sendAccessibilityEvent(AccessibilityDelegateCompat.java:173)
        at androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.sendAccessibilityEvent(AccessibilityDelegateCompat.java:107)
        at android.view.View.sendAccessibilityEvent(View.java:5895)
        at android.view.View$SendViewScrolledAccessibilityEvent.run(View.java:22597)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:191)
        at android.app.ActivityThread.main(ActivityThread.java:5960)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
03-11 12:12:07.419 31229-31229 E/CrashReport: #++++++++++++++++++++++++++++++++++++++++++#

**Comment by zguop** [comment]
@mapsh 必现吗 同学 有什么前置条件没

**Comment by mapsh** [comment]
> @mapsh 必现吗 同学 有什么前置条件没

必现，首页用了轮播图，只要加载出来就崩溃

**Comment by zguop** [comment]
@mapsh 修了问题了。

**Comment by zguop** [comment]
@mapsh 我没有复现，帮忙测试一下  麻烦啦

**Comment by mapsh** [comment]
> @mapsh 我没有复现，帮忙测试一下 麻烦啦
是的，我这里的测试了，没有复现了。
